name: wurp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.00.0"

dependencies:
  flutter:
    sdk: flutter
    
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cupertino_icons: ^1.0.8
  flutter_login: ^6.0.0
  font_awesome_flutter: ^10.12.0
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6
  lottie: ^3.3.0
  path_provider: ^2.1.5
  hive_flutter: ^1.1.0
  stacked_services: ^0.8.6
  get_it: ^7.1.3
  stacked: ^2.1.7
  cached_network_image: ^3.0.0
  provider: ^6.1.5+1
  video_player: ^2.11.0
  fvp: ^0.35.2
  shimmer_animation: ^2.2.2+1
  video_thumbnail: ^0.5.6
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/like.json
    - assets/pixabay_videos.json
    - assets/